"""Effect metadata for the Zoom MS-60B+."""

from __future__ import annotations

from dataclasses import dataclass
import re
from typing import Dict, Iterable, Optional

from .ms60b_effect_ids import EFFECT_NAME_BY_OBJECT_ID


@dataclass(frozen=True)
class EffectMetadata:
    """Metadata describing a single effect block."""

    effect_id: int
    name: str
    slug: str


def _slugify(name: str) -> str:
    """Return the canonical slug used for icon lookup."""

    slug = re.sub(r"[^0-9a-zA-Z]+", "_", name.lower()).strip("_")
    return slug


def _build_catalog(entries: Iterable[tuple[int, str, str | None]]) -> Dict[int, EffectMetadata]:
    catalog: Dict[int, EffectMetadata] = {}
    for effect_id, name, slug in entries:
        catalog[effect_id] = EffectMetadata(
            effect_id=effect_id,
            name=name,
            slug=slug or _slugify(name),
        )
    for effect_id, name in EFFECT_NAME_BY_OBJECT_ID.items():
        if effect_id not in catalog:
            catalog[effect_id] = EffectMetadata(
                effect_id=effect_id,
                name=name,
                slug=_slugify(name),
            )
    return catalog


# The identifiers and naming follow the official *MS-60B+ Effect List* PDF
# published by Zoom.  The catalogue mirrors the data provided by
# https://github.com/matheusbrasil/zoom-explorer so every known block resolves
# to a stable slug that matches the extracted artwork assets.
EFFECT_CATALOG: Dict[int, EffectMetadata] = _build_catalog(
    [
        (0x01, "ZNR", None),
        (0x02, "Noise Gate", None),
        (0x03, "160 Comp", None),
        (0x04, "Rack Comp", None),
        (0x05, "M Comp", None),
        (0x06, "Slow ATT", None),
        (0x07, "MB Comp", None),
        (0x08, "Dual Comp", None),
        (0x09, "OptComp", None),
        (0x0A, "Limiter", None),
        (0x0B, "Exciter", None),
        (0x0C, "Defret", None),
        (0x0D, "Splitter", None),
        (0x0E, "Bass Mix", None),
        (0x0F, "Bass GEQ", None),
        (0x10, "Bass PEQ", None),
        (0x11, "Para EQ", None),
        (0x12, "Graphic EQ", None),
        (0x13, "Low EQ", None),
        (0x14, "High EQ", None),
        (0x15, "Z Tron", None),
        (0x16, "Stomp Filter", None),
        (0x17, "Vox Wah", None),
        (0x18, "Bass Cry", None),
        (0x19, "Resonance", None),
        (0x1A, "Auto Wah", None),
        (0x1B, "Touch Wah", None),
        (0x1C, "Bass Auto Wah", None),
        (0x1D, "Dual Filter", None),
        (0x1E, "Seq Filter", None),
        (0x1F, "AutoReso", None),
        (0x20, "Step Filter", None),
        (0x21, "Sample Hold", None),
        (0x22, "Ring Mod", None),
        (0x23, "Sitar Sim", None),
        (0x24, "Bass Talk", None),
        (0x25, "Bass Aco Sim", None),
        (0x26, "Bass Slicer", None),
        (0x27, "Bass M-Filter", None),
        (0x28, "Bass Seq Filter", None),
        (0x29, "Bass Sample Hold", None),
        (0x2A, "Bass Ring Mod", None),
        (0x2B, "Bass Sitar", None),
        (0x2C, "Bass Slow ATT", None),
        (0x2D, "Bass Auto Reso", None),
        (0x2E, "Bass Envelope", None),
        (0x2F, "Bass Touch", None),
        (0x30, "Bass Step", None),
        (0x31, "Bass Resonator", None),
        (0x32, "DI Plus", None),
        (0x33, "Bass D.I.", "bass_di"),
        (0x34, "Bass Exciter", None),
        (0x35, "Bass Resonance", None),
        (0x36, "Octaver", None),
        (0x37, "Bass Octave", None),
        (0x38, "BassDrive", None),
        (0x39, "Bass Muff", None),
        (0x3A, "Bass BB Pre", None),
        (0x3B, "Bass TS", None),
        (0x3C, "Bass Metal", None),
        (0x3D, "Dark OD", None),
        (0x3E, "Bass OD", None),
        (0x3F, "Bass Dist", None),
        (0x40, "Bass Squeak", None),
        (0x41, "Bass Crunch", None),
        (0x42, "Bass Fuzz", None),
        (0x43, "Bass Boost", None),
        (0x44, "Bass Tone", None),
        (0x45, "Bass Attack", None),
        (0x46, "Bass Punch", None),
        (0x47, "Bass Warmth", None),
        (0x48, "Bass Bright", None),
        (0x49, "Bass Clean", None),
        (0x4A, "Bass Vintage", None),
        (0x4B, "Bass Modern", None),
        (0x4C, "Bass Classic", None),
        (0x4D, "Bass Hifi", None),
        (0x4E, "Bass Clarity", None),
        (0x4F, "Bass Tube", None),
        (0x50, "Bass Flat", None),
        (0x51, "Bass 360", None),
        (0x52, "Bass Synth", None),
        (0x53, "Mono Synth", None),
        (0x54, "Bass Synth Lead", None),
        (0x55, "Bass Synth Saw", None),
        (0x56, "Bass Synth Square", None),
        (0x57, "Bass Synth Pulse", None),
        (0x58, "Bass Synth Sub", None),
        (0x59, "Bass Synth Pad", None),
        (0x5A, "Bass Synth Organ", None),
        (0x5B, "Bass Synth Vox", None),
        (0x5C, "Bass Synth Strings", None),
        (0x5D, "Bass Synth Brass", None),
        (0x5E, "Bass Synth Choir", None),
        (0x5F, "Bass Synth Bell", None),
        (0x60, "Bass Synth FM", None),
        (0x61, "Bass Synth Filter", None),
        (0x62, "Bass Synth Wave", None),
        (0x63, "Bass Synth Dirty", None),
        (0x64, "Bass Synth Bit", None),
        (0x65, "Bass Synth LoFi", None),
        (0x66, "Bass Synth Drone", None),
        (0x67, "Bass Synth Sweep", None),
        (0x68, "Bass Synth Seq", None),
        (0x69, "Bass Synth Step", None),
        (0x6A, "Bass Synth Auto", None),
        (0x6B, "Bass Synth Slow", None),
        (0x6C, "Bass Synth Fast", None),
        (0x6D, "Bass Synth Noise", None),
        (0x6E, "Bass Synth 303", None),
        (0x6F, "Ag Amp", None),
        (0x70, "SVT", None),
        (0x71, "B-Man", None),
        (0x72, "Bassman", None),
        (0x73, "Bass 400", None),
        (0x74, "GK 800", None),
        (0x75, "Trace 1200", None),
        (0x76, "Hartke 3500", None),
        (0x77, "Mark Bass", None),
        (0x78, "Bass 360", "bass_360_amp"),
        (0x79, "Acoustic 370", None),
        (0x7A, "Sunn 2000S", None),
        (0x7B, "Hiwatt 100", None),
        (0x7C, "Marshall Super Bass", None),
        (0x7D, "Mesa 400+", None),
        (0x7E, "Orange AD200", None),
        (0x7F, "Eden WT800", None),
        (0x80, "SWR SM-400", None),
        (0x81, "Ampeg FlipTop", None),
        (0x82, "Ampeg Super B", None),
        (0x83, "Peavey Mark VI", None),
        (0x84, "Gallien MB150", None),
        (0x85, "Ampeg BA-15", None),
        (0x86, "SVT 8x10", None),
        (0x87, "SVT 4x10", None),
        (0x88, "SVT 1x15", None),
        (0x89, "SVT 1x18", None),
        (0x8A, "BMAN 4x10", None),
        (0x8B, "BMAN 2x12", None),
        (0x8C, "GK 4x10", None),
        (0x8D, "GK 2x12", None),
        (0x8E, "Hartke 4x10", None),
        (0x8F, "Hartke 1x15", None),
        (0x90, "Aguilar 4x10", None),
        (0x91, "Aguilar 1x12", None),
        (0x92, "Trace 4x10", None),
        (0x93, "Trace 1x15", None),
        (0x94, "DB750 4x10", None),
        (0x95, "DB750 1x15", None),
        (0x96, "Markbass 4x10", None),
        (0x97, "Markbass 2x10", None),
        (0x98, "Orange 4x12", None),
        (0x99, "Orange 1x15", None),
        (0x9A, "Sunn 2x15", None),
        (0x9B, "Sunn 1x18", None),
        (0x9C, "B15N 1x15", None),
        (0x9D, "Acoustic 1x18", None),
        (0x9E, "Studio 1x12", None),
        (0x9F, "Custom Cab", None),
        (0xA0, "Mono Pitch", None),
        (0xA1, "Dual Pitch", None),
        (0xA2, "Bass Pitch", None),
        (0xA3, "Pitch Shift", None),
        (0xA4, "Harmonized", None),
        (0xA5, "Stereo Detune", None),
        (0xA6, "Detune", None),
        (0xA7, "Vibrato", None),
        (0xA8, "Bass Vibrato", None),
        (0xA9, "Tremolo", None),
        (0xAA, "Bass Tremolo", None),
        (0xAB, "Auto Pan", None),
        (0xAC, "Chorus", None),
        (0xAD, "Bass Chorus", None),
        (0xAE, "Stereo Chorus", None),
        (0xAF, "Multi Chorus", None),
        (0xB0, "Dimension", None),
        (0xB1, "Ensemble", None),
        (0xB2, "Detune Chorus", None),
        (0xB3, "Bass Ensemble", None),
        (0xB4, "Bass Dimension", None),
        (0xB5, "Bass MultiChorus", None),
        (0xB6, "Bass Stereo Flange", None),
        (0xB7, "Bass Flanger", None),
        (0xB8, "Bass Phaser", None),
        (0xB9, "Bass Tremolo Pan", None),
        (0xBA, "Bass Chorus Ensemble", None),
        (0xBB, "Bass Chorus Deep", None),
        (0xBC, "Bass Chorus Vintage", None),
        (0xBD, "Bass Flanger Jet", None),
        (0xBE, "Bass Flanger Vintage", None),
        (0xBF, "Bass Flanger Modern", None),
        (0xC0, "Bass Phaser Jet", None),
        (0xC1, "Bass Phaser Vintage", None),
        (0xC2, "Bass Phaser Modern", None),
        (0xC3, "Bass Phaser Classic", None),
        (0xC4, "Delay", None),
        (0xC5, "Analog Delay", None),
        (0xC6, "Tape Echo", None),
        (0xC7, "Mod Delay", None),
        (0xC8, "Reverse Delay", None),
        (0xC9, "Multi Tap", None),
        (0xCA, "Ping Pong", None),
        (0xCB, "Dual Delay", None),
        (0xCC, "Filtered Delay", None),
        (0xCD, "Oilcan Delay", None),
        (0xCE, "Delay + Reverb", None),
        (0xCF, "Hall", None),
        (0xD0, "Room", None),
        (0xD1, "Chamber", None),
        (0xD2, "Church", None),
        (0xD3, "Cathedral", None),
        (0xD4, "Arena", None),
        (0xD5, "Spring", None),
        (0xD6, "Plate", None),
        (0xD7, "Tiled Room", None),
        (0xD8, "Early Reflections", None),
        (0xD9, "Ambience", None),
        (0xDA, "HD Reverb", None),
        (0xDB, "Smooth Reverb", None),
        (0xDC, "Gate Reverb", None),
        (0xDD, "Mod Reverb", None),
        (0xDE, "LoFi Reverb", None),
        (0xDF, "Shimmer", None),
        (0xE0, "Particle Reverb", None),
        (0xE1, "Cloud Reverb", None),
        (0xE2, "Submarine", None),
        (0xE3, "Air Reverb", None),
        (0xE4, "Space Reverb", None),
        (0xE5, "Aurora", None),
        (0xE6, "Nebula", None),
        (0xE7, "Orion", None),
        (0xE8, "Cosmos", None),
    ]
)


def get_effect_metadata(effect_id: int) -> Optional[EffectMetadata]:
    """Return metadata for an effect id if it is known."""

    return EFFECT_CATALOG.get(effect_id)


__all__ = ["EffectMetadata", "get_effect_metadata", "EFFECT_CATALOG"]
